### ISSUE TITLE
Unable to Install/Download

### ISSUE THREAD

**Issue by slehan** [dotnet/ResXResourceManager#322]
Hi there,

I was trying to install the standalone version of ResXResourceManager. I tried [this link from the README](https://clickonce-tom-englert.azurewebsites.net/ResXResourceManager/ResXManager.application) for the one click install and it responds with "Error 403 - This web app is stopped.".

I tried the standalone installer from the repositories releases, which the installer fails with a similar error:
```
An error occurred trying to download 'https://clickonce-tom-englert.azurewebsites.net/ResXResourceManager/ResXManager.application'.
```

It seems like the server the download is hosted is on, is down.

**Comment by tom-englert** [comment]
Must have been a temporary downtime, it's working fine now.

**Comment by tom-englert** [comment]
BTW, the issue might be also on your side:

HTTP 403 is a standard HTTP status code communicated to clients by an HTTP server to indicate that access to the requested URL by the client is forbidden for some reason. **The server understood the request, but will not fulfill it due to client related issues**
