### ISSUE TITLE
Authentication for Azure

### ISSUE THREAD

**Issue by Rodric75** [dotnet/ResXResourceManager#368]
In order to make use of the key from Azure Cognitive Services I had to make a change to AzureAuthentication.cs line 12 to include the region of the key.  

In my case : 
`private static readonly Uri _serviceUrl = new Uri("https://westus2.api.cognitive.microsoft.com/sts/v1.0/issueToken");`

[Authenticate requests to Azure Cognitive Services](https://docs.microsoft.com/en-us/azure/cognitive-services/authentication?tabs=powershell#authenticate-with-a-single-service-subscription-key) describes the available regions

**Describe the bug**
Token service for cognitive services requires the region to be prepended to the uri or access is denied.

**To Reproduce**
Get a key from Cognitive Services / Keys and Endpoint / Key 1
Paste that value into textbox label Key:

**Expected behavior**
Token retrieved

**Comment by tom-englert** [comment]
If you move it to the global location, as mentioned here: #321, it will work.

However if s.o. comes up with a PR to make this configurable, I'll be happy to merge it.

**Comment by MikeFH** [comment]
@tom-englert I had the same problem.
After looking at the [documentation](https://docs.microsoft.com/en-us/azure/cognitive-services/translator/reference/v3-0-reference#authentication) and a bit at the code, I feel like the authentication with a secret key could be used instead of the authentication with an access token. The [AzureAuthentication](https://github.com/dotnet/ResXResourceManager/blob/master/src/ResXManager.Translators/AzureAuthentication.cs) class could be removed for simplicity. An optional textbox could then be added in the AzureTranslatorConfiguration.xaml to populate the `Ocp-Apim-Subscription-Region` header if the user needs it.

If this seems ok for you, I can try to submit a pull request.

**Comment by tom-englert** [comment]
@MikeFH sounds good! I have prepared the UI so the region can be already specified, so you can implement the logic.
Please use branch `#368` (https://github.com/dotnet/ResXResourceManager/tree/%23368)

**Comment by tom-englert** [comment]
Fixed via #389

**Comment by tom-englert** [comment]
Fixed via #389
