### ISSUE TITLE
Window does not open. Error: Set Property

### ISSUE THREAD

**Issue by Henry948** [dotnet/ResXResourceManager#421]
**Important**
**Describe the bug**
When selecting the extension from the toolbar the window does not open and the request does not complete. This has been installed on VS2017.

**Expected behavior**
We expect the window to open and us to be able to edit the strings needing to be translated within that window

here is a copy of the error message, 
Error: Set property 'System.Windows.ResourceDictionary.DeferrableContent' threw an exception.
 ---> Provide value on 'MS.Internal.Markup.StaticExtension' threw an exception.
 ---> Could not load file or assembly 'TomsToolbox.Wpf.Styles, PublicKeyToken=60b39f873a8e3fc2' or one of its dependencies. The system cannot find the file specified.

NOTE: We have read through the documentation and tried every step within the troubleshooting area and to no avail, we have no luck. It is rather confusing saying it is working fine on one machine for a colleague but not for myself.

**Comment by tom-englert** [comment]
Sorry, but loading the extension and it's dependencies is part of Visual Studio, not the extension itself. 
There is nothing I can do about this, please raise an issue for Visual Studio.

**Comment by burukan** [comment]
Hey @tom-englert, I had a similar extension problem and it fixed itself on yesterdays build (Visual Studio 2019 version 16.11.0). Guess you may add this to important document so that people try updating and report back as well.

`
SetSite failed for package [VsPackage]Source: 'mscorlib' Description: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)   at System.Reflection.RuntimeAssembly.get_DefinedTypes()   at TomsToolbox.Composition.MetadataReader.Read(Assembly assembly) in D:\a\1\s\src\TomsToolbox.Composition\MetadataReader.cs:line 29   at System.Linq.Enumerable.&lt;SelectManyIterator&gt;d__17`2.MoveNext()   at TomsToolbox.Composition.Ninject.ExtensionMethods.BindExports(IKernel kernel, IEnumerable`1 exportInfos) in D:\a\1\s\src\TomsToolbox.Composition.Ninject\ExtensionMethods.cs:line 44   at TomsToolbox.Composition.Ninject.ExtensionMethods.BindExports(IKernel kernel, IEnumerable`1 assemblies) in D:\a\1\s\src\TomsToolbox.Composition.Ninject\ExtensionMethods.cs:line 34   at ResXManager.VSIX.VsPackage.FillCatalog() in D:\a\1\s\src\ResXManager.VSIX\VSPackage.cs:line 193   at System.Threading.Tasks.Task`1.InnerInvoke()   at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)   at ResXManager.VSIX.VsPackage.&lt;InitializeAsync&gt;d__16.MoveNext() in D:\a\1\s\src\ResXManager.VSIX\VSPackage.cs:line 101 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.VisualStudio.Shell.UIThreadReentrancyScope.WaitOnTaskCompleteInternal(Task task, CancellationToken cancel, Int32 ms)   at Microsoft.VisualStudio.Services.VsTask.&lt;&gt;c__DisplayClass100_1.&lt;InternalGetResult&gt;b__1()   at Microsoft.VisualStudio.Services.VsTask.IgnoreObjectDisposedException(Action action)   at Microsoft.VisualStudio.Services.VsTask.&lt;&gt;c__DisplayClass100_0.&lt;InternalGetResult&gt;b__0()   at Microsoft.VisualStudio.Services.VsTask.&lt;&gt;c__DisplayClass108_0.&lt;InvokeWithWaitDialog&gt;b__0()   at Microsoft.VisualStudio.Services.VsTask.InvokeWithWaitDialog[T](Func`1 function)   at Microsoft.VisualStudio.Services.VsTask.InvokeWithWaitDialog(Action action)   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)   at Microsoft.VisualStudio.Services.VsTask.GetResult()`

**Comment by andrea60** [comment]
Happened the same as @burukan. I had the same problem, which disappeared after updating to VS2019 version 16.11.2

**Comment by tom-englert** [comment]
Looks like this can be closed.
