### ISSUE TITLE
Detect code references: Find usages across multiple projects inside same solution

### ISSUE THREAD

**Issue by BujusKrachus** [dotnet/ResXResourceManager#588]
**Describe the bug**
"Detect code references" won't list resource references across multiple projects in the same solution in current version of vs-extension.
Don't know if this is considered a bug or feature request.

**To Reproduce**
- Create a new visual studio solution
- Create a project, which will be used as a global resource project of the solution
- Create resource files and enter some string values. Don't forget to make it public to use in other projects.
- Create a new project inside the solution and reference some of the resource keys here. First add the resource project as project reference.
- Code references from the actual code project will not be listed even though i would expect them to as the extension is opened solution wide.

Project structure should look like this to reproduce bug:
![image](https://github.com/dotnet/ResXResourceManager/assets/58236589/cbbeb294-a7a8-4704-bddd-56f6e3384022)

**Expected behavior**
Code reference should list all occurences across all projects inside the same solution.

**Comment by tom-englert** [comment]
That works, since code references are only scanned by text, ignoring project or solution structure.
Maybe you can post your sample to see what's wrong in there?

**Comment by tom-englert** [comment]
In can't work using such a heavy abstraction, since the algorithm is language agnostic (See https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Detect-Code-References.md)
```
using res = ResourcesSample.Resource1;

Console.WriteLine(res.String1);
```
That also would not have work in the same project, so this is also a false assumption that could have been tested before:
> Detect code references" won't list resource references across multiple projects

Using some cleaner code it will work out of the box.
```
using ResourcesSample;

Console.WriteLine(Resource1.String1);
```
However feel free to adapt the patterns to your needs if you are using some special conventions.
