### ISSUE TITLE
ResX Manager extension stopped working in VS2019

### ISSUE THREAD

**Issue by BillClarkDemTech** [dotnet/ResXResourceManager#663]
The ResX Manager extension was working great in VS2019, but today it won't load. It pops up the attached message box, ![ResxManager](https://github.com/user-attachments/assets/cba77d24-0e36-4af5-adbc-1907b548b43f)
and the VS activity log has entries like the following: 

  <entry>
    <record>728</record>
    <time>2024/09/23 21:05:06.567</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [VsPackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;System.Composition.AttributedModel, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The located assembly&apos;s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)&#x000D;&#x000A;System.IO.FileLoadException: Could not load file or assembly &apos;System.Composition.AttributedModel, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The located assembly&apos;s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)&#x000D;&#x000A;File name: &apos;System.Composition.AttributedModel, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)&#x000D;&#x000A;   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)&#x000D;&#x000A;   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)&#x000D;&#x000A;   at System.Reflection.CustomAttributeData..ctor(RuntimeModule scope, CustomAttributeRecord caRecord)&#x000D;&#x000A;   at System.Reflection.CustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)&#x000D;&#x000A;   at System.Reflection.CustomAttributeData.GetCustomAttributesInternal(RuntimeType target)&#x000D;&#x000A;   at System.RuntimeType.GetCustomAttributesData()&#x000D;&#x000A;   at TomsToolbox.Composition.MetadataReader.ReadType(TypeInfo typeInfo, IList`1 result) in D:\a\1\s\src\TomsToolbox.Composition\MetadataReader.cs:line 42&#x000D;&#x000A;   at TomsToolbox.Composition.MetadataReader.ReadTypes(IEnumerable`1 typeInfos, IList`1 result) in D:\a\1\s\src\TomsToolbox.Composition\MetadataReader.cs:line 34&#x000D;&#x000A;   at TomsToolbox.Composition.MetadataReader.Read(Assembly assembly) in D:\a\1\s\src\TomsToolbox.Composition\MetadataReader.cs:line 25&#x000D;&#x000A;   at System.Linq.Enumerable.&lt;SelectManyIterator&gt;d__17`2.MoveNext()&#x000D;&#x000A;   at TomsToolbox.Composition.Ninject.ExtensionMethods.BindExports(IKernel kernel, IEnumerable`1 exportInfos) in D:\a\1\s\src\TomsToolbox.Composition.Ninject\ExtensionMethods.cs:line 41&#x000D;&#x000A;   at TomsToolbox.Composition.Ninject.ExtensionMethods.BindExports(IKernel kernel, IEnumerable`1 assemblies) in D:\a\1\s\src\TomsToolbox.Composition.Ninject\ExtensionMethods.cs:line 31&#x000D;&#x000A;   at ResXManager.VSIX.VsPackage.FillCatalog() in D:\a\1\s\src\ResXManager.VSIX\VSPackage.cs:line 194&#x000D;&#x000A;   at System.Threading.Tasks.Task`1.InnerInvoke()&#x000D;&#x000A;   at System.Threading.Tasks.Task.Execute()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at ResXManager.VSIX.VsPackage.&lt;InitializeAsync&gt;d__15.MoveNext() in D:\a\1\s\src\ResXManager.VSIX\VSPackage.cs:line 102&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__76.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()&#x000D;&#x000A;&#x000D;&#x000A;Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll&#x000D;&#x000A;Running under executable  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe&#x000D;&#x000A;--- A detailed error log follows. &#x000A;&#x000D;&#x000A;=== Pre-bind state information ===&#x000D;&#x000A;LOG: DisplayName = System.Composition.AttributedModel, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&#x000A; (Fully-specified)&#x000D;&#x000A;LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/&#x000D;&#x000A;LOG: Initial PrivatePath = NULL&#x000D;&#x000A;Calling assembly : TomsToolbox.Wpf.Composition.AttributedModel, Version=2.18.1.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2.&#x000D;&#x000A;===&#x000D;&#x000A;LOG: This bind starts in default load context.&#x000D;&#x000A;LOG: Using application configuration file: C:\Users\Bill Clark\AppData\Local\Microsoft\VisualStudio\16.0_67673c38\devenv.exe.config&#x000D;&#x000A;LOG: Using host configuration file: &#x000D;&#x000A;LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.&#x000D;&#x000A;LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/System.Composition.AttributedModel.DLL.&#x000D;&#x000A;LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/System.Composition.AttributedModel/System.Composition.AttributedModel.DLL.&#x000D;&#x000A;LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/PublicAssemblies/System.Composition.AttributedModel.DLL.&#x000D;&#x000A;LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/PublicAssemblies/System.Composition.AttributedModel/System.Composition.AttributedModel.DLL.&#x000D;&#x000A;LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/PrivateAssemblies/System.Composition.AttributedModel.DLL.&#x000D;&#x000A;WRN: Comparing the assembly name resulted in the mismatch: Major Version&#x000D;&#x000A;ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.&#x000D;&#x000A;</description>
    <guid>{43B35FE0-1F30-48DE-887A-68256474202A}</guid>
    <hr>80131040</hr>
    <errorinfo></errorinfo>
  </entry>

**To Reproduce**
Bring up VS2019

**Expected behavior**
ResX Manager extension loads.

**Comment by BillClarkDemTech** [comment]
I have disabled the extension and re-enabled; uninstalled it and reinstalled; repaired and updated VS2019; started VS with admin rights; deleted the path C:\Users\{user name}\AppData\Roaming\Microsoft\VisualStudio\16.0_67673c38. All to no avail. The standalone version of ResX Manager is working.

**Comment by tom-englert** [comment]
OK, sorry, but in this case I have to drop VS2019 support, as it's too much effort to keep the whole dependency chain backward compatible with outdated components.

You can still download the VSIX package from the last working release from the release page, and disable automatic update for this package.

**Comment by Robo90** [comment]
Since yesterday I have the same problem under Visual Studio 2022. I have reinstalled it without success.

![grafik](https://github.com/user-attachments/assets/99a0ddfe-4ccc-4a75-a6d2-cbb3c95eda89)

_SetSite failed for package [VsPackage]Source: &apos;mscorlib&apos; Description: Die Datei oder Assembly &quot;System.Composition.AttributedModel, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&quot; oder eine Abh&#x00E4;ngigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis &#x00FC;berein. (Ausnahme von HRESULT: 0x80131040)&#x000D;&#x000A;System.IO.FileLoadException: Die Datei oder Assembly &quot;System.Composition.AttributedModel, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&quot; oder eine Abh&#x00E4;ngigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis &#x00FC;berein. (Ausnahme von HRESULT: 0x80131040)&#x000D;&#x000A;Dateiname: &quot;System.Composition.AttributedModel, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&quot;&#x000D;&#x000A;   bei System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)&#x000D;&#x000A;   bei System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)&#x000D;&#x000A;   bei System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)&#x000D;&#x000A;   bei System.Reflection.CustomAttributeData..ctor(RuntimeModule scope, CustomAttributeRecord caRecord)&#x000D;&#x000A;   bei System.Reflection.CustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)&#x000D;&#x000A;   bei System.Reflection.CustomAttributeData.GetCustomAttributesInternal(RuntimeType target)&#x000D;&#x000A;   bei TomsToolbox.Composition.MetadataReader.ReadType(TypeInfo typeInfo, IList`1 result) in D:\a\1\s\src\TomsToolbox.Composition\MetadataReader.cs:Zeile 42.&#x000D;&#x000A;   bei TomsToolbox.Composition.MetadataReader.ReadTypes(IEnumerable`1 typeInfos, IList`1 result) in D:\a\1\s\src\TomsToolbox.Composition\MetadataReader.cs:Zeile 32.&#x000D;&#x000A;   bei TomsToolbox.Composition.MetadataReader.Read(Assembly assembly) in D:\a\1\s\src\TomsToolbox.Composition\MetadataReader.cs:Zeile 27.&#x000D;&#x000A;   bei System.Linq.Enumerable.&lt;SelectManyIterator&gt;d__17`2.MoveNext()&#x000D;&#x000A;   bei TomsToolbox.Composition.Ninject.ExtensionMethods.BindExports(IKernel kernel, IEnumerable`1 exportInfos) in D:\a\1\s\src\TomsToolbox.Composition.Ninject\ExtensionMethods.cs:Zeile 41.&#x000D;&#x000A;   bei ResXManager.VSIX.VsPackage.FillCatalog() in D:\a\1\s\src\ResXManager.VSIX\VSPackage.cs:Zeile 201.&#x000D;&#x000A;   bei System.Threading.Tasks.Task`1.InnerInvoke()&#x000D;&#x000A;   bei System.Threading.Tasks.Task.Execute()&#x000D;&#x000A;--- Ende der Stapel&#x00FC;berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel&#x00F6;st wurde ---&#x000D;&#x000A;   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   bei ResXManager.VSIX.VsPackage.&lt;InitializeAsync&gt;d__15.MoveNext() in D:\a\1\s\src\ResXManager.VSIX\VSPackage.cs:Zeile 102.&#x000D;&#x000A;--- Ende der Stapel&#x00FC;berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel&#x00F6;st wurde ---&#x000D;&#x000A;   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   bei Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass21_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- Ende der Stapel&#x00FC;berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel&#x00F6;st wurde ---&#x000D;&#x000A;   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   bei Microsoft.VisualStudio.Shell.UIThreadReentrancyScope.WaitOnTaskCompleteInternal(Task task, CancellationToken cancel, Int32 ms)&#x000D;&#x000A;   bei Microsoft.VisualStudio.Services.VsTask.&lt;&gt;c__DisplayClass68_1.&lt;InternalGetResult&gt;b__1()&#x000D;&#x000A;   bei Microsoft.VisualStudio.Services.VsTask.IgnoreObjectDisposedException(Action action)&#x000D;&#x000A;   bei Microsoft.VisualStudio.Services.VsTask.&lt;&gt;c__DisplayClass68_0.&lt;InternalGetResult&gt;b__0()&#x000D;&#x000A;   bei Microsoft.VisualStudio.Services.VsTask.&lt;&gt;c__DisplayClass76_0.&lt;InvokeWithWaitDialog&gt;b__0()&#x000D;&#x000A;   bei Microsoft.VisualStudio.Services.VsTask.InvokeWithWaitDialog[T](Func`1 function)&#x000D;&#x000A;   bei Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Protokollierung der Assemblybindung ist AUS.&#x000D;&#x000A;Sie k&#x00F6;nnen die Protokollierung der Assemblybindungsfehler aktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) auf 1 festlegen.&#x000D;&#x000A;Hinweis: Die Protokollierung der Assemblybindungsfehler f&#x00FC;hrt zu einer gewissen Leistungseinbu&#x00DF;e.&#x000D;&#x000A;Sie k&#x00F6;nnen dieses Feature deaktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] entfernen.&#x000D;&#x000A;_

**Comment by SehlingS** [comment]
The same on my side with VS 2022 Version 17.8.3.
Do you have an idea?

**Comment by tom-englert** [comment]
Can someone try this version: https://www.vsixgallery.com/extension/43b35fe0-1f30-48de-887a-68256474202a

**Comment by BillClarkDemTech** [comment]
Working on VS2019 as well. Thank you!!

**Comment by roimvsao** [comment]
Do you think changes will fix also VS2017 compatibility? 
The provided link won't install extension for VS2017 though

**Comment by tom-englert** [comment]
@roimvsao no, sorry https://github.com/dotnet/ResXResourceManager/releases/tag/1.89
